In [1]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [2]:
# 读取Excel文件
data = pd.read_excel('HotelCustomersDataset.xlsx')

# 打印DataFrame的前几行进行检查
data.head()

C:\Users\pxy18\anaconda3\Lib\site-packages\openpyxl\packaging\core.py:99: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now = datetime.datetime.utcnow()
C:\Users\pxy18\anaconda3\Lib\site-packages\openpyxl\packaging\core.py:99: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now = datetime.datetime.utcnow()

,ID,Nationality,Age,DaysSinceCreation,NameHash,DocIDHash,AverageLeadTime,LodgingRevenue,OtherRevenue,BookingsCanceled,...,SRMediumFloor,SRBathtub,SRShower,SRCrib,SRKingSizeBed,SRTwinBed,SRNearElevator,SRAwayFromElevator,SRNoAlcoholInMiniBar,SRQuietRoom
0,1,PRT,51.0,150,0x8E0A7AF39B633D5EA25C3B7EF4DFC5464B36DB7AF375...,0x71568459B729F7A7ABBED6C781A84CA4274D571003AC...,45,371.0,105.3,1,...,0,0,0,0,0,0,0,0,0,0
1,2,PRT,NaN,1095,0x21EDE41906B45079E75385B5AA33287CA09DE1AB86DE...,0x5FA1E0098A31497057C5A6B9FE9D49FD6DD47CCE7C26...,61,280.0,53.0,0,...,0,0,0,0,0,0,0,0,0,0
2,3,DEU,31.0,1095,0x31C5E4B74E23231295FDB724AD578C02C4A723F4BA2B...,0xC7CF344F5B03295037595B1337AC905CA188F1B5B3A5...,0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,FRA,60.0,1095,0xFF534C83C0EF23D1CE516BC80A65D0197003D27937D4...,0xBD3823A9B4EC35D6CAF4B27AE423A677C0200DB61E82...,93,240.0,60.0,0,...,0,0,0,0,0,0,0,0,0,0
4,5,FRA,51.0,1095,0x9C1DEF02C9BE242842C1C1ABF2C5AA249A1EEB4763B4...,0xE175754CF77247B202DD0820F49407C762C14A603B3A...,0,0.0,0.0,0,...,0,0,0,0,0,0,0,0,0,0

In [5]:
#存个档
kaka=data

In [7]:
#重开了直接运行这里
data=kaka

In [19]:
kaka.shape

(83590, 31)

字段解释：


ID：客户的唯一标识符。
Nationality：客户的国籍。
Age：客户的年龄。
DaysSinceCreation：自账户创建以来的天数。
--NameHash：客户姓名的哈希值（加密形式）。
--DocIDHash：身份证件号码的哈希值（加密形式）。
AverageLeadTime：平均预订时间（从预订到入住的天数）。
LodgingRevenue：住宿收入。
OtherRevenue：其他服
务或设施的收入。

BookingsCanceled：取消的预订数量。
BookingsNoShowed：未出现的预订数量（即客人没有如约到达）。
BookingsCheckedIn：已办理入住手续的预订数量。
PersonsNights：总人夜数（每位客人每晚算一个单位）。
RoomNights：房间夜数（每间房每晚算一个单位）。
DaysSinceLastStay：上次住宿至今的天数。
DaysSinceFirs
tStay：首次住宿至今的天数。

DistributionChannel：分销渠道（例如在线旅行社、直接预订等）。
MarketSegment：市场细分（
根据客人的类型或来源划分的市场群体）。

SRHighFloor：是否需要高层房间。
SRLowFloor：是否需要低层房间。
SRAccessibleRoom：是否需要无障碍通道房间。
SRMediumFloor：是否需要中层房间。
SRBathtub：是否需要带浴缸的房间。
SRShower：是否需要带淋浴的房间。
SRCrib：是否需要婴儿床。
SRKingSizeBed：是否需要特大号床。
SRTwinBed：是否需要双人床。
SRNearElevator：是否需要靠近电梯的房间。
SRAwayFromElevator：是否需要远离电梯的房间。
SRNoAlcoholInMiniBar：是否需要在迷你吧中不放置酒精饮料。
SRQuietRoom：是否需要安静的房间。

*探索分销渠道与预订结果的关联:比较通过不同分销渠道预订的客户在取消率、未出现率和回头客方面的差异。*


前项为DistributionChannel、MarketSegment。


后项为BookingsCanceled、BookingsNoShowed、BookingsCheckedIn。

In [9]:
#选择我们需要的属性（对应过滤器）
data = data[['ID',#标识字段
         'DistributionChannel', 'MarketSegment',#前项
         'BookingsCanceled','BookingsNoShowed','BookingsCheckedIn']]#后项

# 打印DataFrame的前几行进行检查
data.head(10)

,ID,DistributionChannel,MarketSegment,BookingsCanceled,BookingsNoShowed,BookingsCheckedIn
0,1,Corporate,Corporate,1,0,3
1,2,Travel Agent/Operator,Travel Agent/Operator,0,0,1
2,3,Travel Agent/Operator,Travel Agent/Operator,0,0,0
3,4,Travel Agent/Operator,Travel Agent/Operator,0,0,1
4,5,Travel Agent/Operator,Travel Agent/Operator,0,0,0
5,6,Travel Agent/Operator,Other,0,0,1
6,7,Travel Agent/Operator,Other,0,0,0
7,8,Travel Agent/Operator,Other,0,0,1
8,9,Travel Agent/Operator,Other,0,0,0
9,10,Travel Agent/Operator,Travel Agent/Operator,0,0,1

对BookingsCanceled、BookingsNoShowed、BookingsCheckedIn的值进行重新分组

In [11]:
#对BookingsCanceled、BookingsNoShowed、BookingsCheckedIn进行二元化（非0即1）
def to_brinary(value):
    if value == 0:
        return False
    else:
        return True

data['BookingsCanceled'] = data['BookingsCanceled'].apply(to_brinary)
data['BookingsNoShowed'] = data['BookingsNoShowed'].apply(to_brinary)
data['BookingsCheckedIn'] = data['BookingsCheckedIn'].apply(to_brinary)

data.head(10)

C:\Users\pxy18\AppData\Local\Temp\ipykernel_15228\1199226193.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['BookingsCanceled'] = data['BookingsCanceled'].apply(to_brinary)
C:\Users\pxy18\AppData\Local\Temp\ipykernel_15228\1199226193.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['BookingsNoShowed'] = data['BookingsNoShowed'].apply(to_brinary)
C:\Users\pxy18\AppData\Local\Temp\ipykernel_15228\1199226193.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['BookingsCheckedIn'] = data['BookingsCheckedIn'].apply(to_brinary)

,ID,DistributionChannel,MarketSegment,BookingsCanceled,BookingsNoShowed,BookingsCheckedIn
0,1,Corporate,Corporate,True,False,True
1,2,Travel Agent/Operator,Travel Agent/Operator,False,False,True
2,3,Travel Agent/Operator,Travel Agent/Operator,False,False,False
3,4,Travel Agent/Operator,Travel Agent/Operator,False,False,True
4,5,Travel Agent/Operator,Travel Agent/Operator,False,False,False
5,6,Travel Agent/Operator,Other,False,False,True
6,7,Travel Agent/Operator,Other,False,False,False
7,8,Travel Agent/Operator,Other,False,False,True
8,9,Travel Agent/Operator,Other,False,False,False
9,10,Travel Agent/Operator,Travel Agent/Operator,False,False,True

In [13]:
# 对前项进行独热编码
encoded_data = pd.get_dummies(data[['DistributionChannel', 'MarketSegment']])

# 选取后项列进行独热编码
back_items = pd.get_dummies(data[['BookingsCanceled', 'BookingsNoShowed', 'BookingsCheckedIn']])

# 合并编码后的前项和后项
combined_data = pd.concat([encoded_data, back_items], axis=1)

# 使用 Apriori 算法计算频繁项集
frequent_itemsets = apriori(combined_data, min_support=0.1, use_colnames=True)

# 生成关联规则
rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.7)

# 筛选出前项为 DistributionChannel 和 MarketSegment 独热编码后的列，后项为指定后项列的规则
desired_rules = rules[(rules['antecedents'].apply(lambda x: all(col.split('_')[0] in ['DistributionChannel', 'MarketSegment'] for col in x)) &
                       rules['consequents'].apply(lambda x: all(col in back_items.columns for col in x)))]

desired_rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
2,(DistributionChannel_Direct),(BookingsCheckedIn),0.142505,0.761694,0.102393,0.718519,0.943317,-0.006153,0.846615,-0.065486
6,(DistributionChannel_Travel Agent/Operator),(BookingsCheckedIn),0.820301,0.761694,0.625135,0.762079,1.000506,0.000316,1.001619,0.002812
8,(MarketSegment_Other),(BookingsCheckedIn),0.574698,0.761694,0.427288,0.743500,0.976114,-0.010456,0.929069,-0.054407
9,(MarketSegment_Travel Agent/Operator),(BookingsCheckedIn),0.139610,0.761694,0.111078,0.795630,1.044553,0.004738,1.166051,0.049574
10,"(DistributionChannel_Travel Agent/Operator, Ma...",(BookingsCheckedIn),0.567209,0.761694,0.420433,0.741231,0.973135,-0.011607,0.920923,-0.059962
14,"(MarketSegment_Travel Agent/Operator, Distribu...",(BookingsCheckedIn),0.138103,0.761694,0.109654,0.794006,1.042421,0.004462,1.156856,0.047215

In [15]:
rules.head(10)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(DistributionChannel_Direct),(MarketSegment_Direct),0.142505,0.137062,0.134215,0.941823,6.871521,0.114683,14.833073,0.996474
1,(MarketSegment_Direct),(DistributionChannel_Direct),0.137062,0.142505,0.134215,0.979227,6.871521,0.114683,41.278652,0.990189
2,(DistributionChannel_Direct),(BookingsCheckedIn),0.142505,0.761694,0.102393,0.718519,0.943317,-0.006153,0.846615,-0.065486
3,(MarketSegment_Groups),(DistributionChannel_Travel Agent/Operator),0.113662,0.820301,0.106329,0.935480,1.140411,0.013091,2.785181,0.138912
4,(MarketSegment_Other),(DistributionChannel_Travel Agent/Operator),0.574698,0.820301,0.567209,0.986969,1.203178,0.095783,13.789996,0.397054
5,(MarketSegment_Travel Agent/Operator),(DistributionChannel_Travel Agent/Operator),0.139610,0.820301,0.138103,0.989203,1.205902,0.023580,16.643507,0.198451
6,(DistributionChannel_Travel Agent/Operator),(BookingsCheckedIn),0.820301,0.761694,0.625135,0.762079,1.000506,0.000316,1.001619,0.002812
7,(BookingsCheckedIn),(DistributionChannel_Travel Agent/Operator),0.761694,0.820301,0.625135,0.820716,1.000506,0.000316,1.002313,0.002120
8,(MarketSegment_Other),(BookingsCheckedIn),0.574698,0.761694,0.427288,0.743500,0.976114,-0.010456,0.929069,-0.054407
9,(MarketSegment_Travel Agent/Operator),(BookingsCheckedIn),0.139610,0.761694,0.111078,0.795630,1.044553,0.004738,1.166051,0.049574